os:
  - linux
  - osx
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
sudo: required
dist: trusty
env:
  - NODE_ENV=PROD
before_install:
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CHROME_BIN=/usr/bin/google-chrome; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update ; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo dpkg -i google-chrome*.deb; fi
install:
  - npm install
  - npm run install-selenium
before_script:
  - npm run build
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use oraclejdk8; fi
  - npm run test
